version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: plataforma_cursos_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: plataforma_cursos
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 